/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as aiLlmsFullDottxtRouteImport } from './routes/(ai)/llms-full[.]txt'
import { Route as aiLlmsDottxtRouteImport } from './routes/(ai)/llms[.]txt'
import { Route as aiChar123Char125DotmdRouteImport } from './routes/(ai)/{$}[.]md'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const aiLlmsFullDottxtRoute = aiLlmsFullDottxtRouteImport.update({
  id: '/(ai)/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const aiLlmsDottxtRoute = aiLlmsDottxtRouteImport.update({
  id: '/(ai)/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const aiChar123Char125DotmdRoute = aiChar123Char125DotmdRouteImport.update({
  id: '/(ai)/{$}.md',
  path: '/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof aiLlmsFullDottxtRoute
  '/llms.txt': typeof aiLlmsDottxtRoute
  '/{$}.md': typeof aiChar123Char125DotmdRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/llms-full.txt': typeof aiLlmsFullDottxtRoute
  '/llms.txt': typeof aiLlmsDottxtRoute
  '/{$}.md': typeof aiChar123Char125DotmdRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/(ai)/llms-full.txt': typeof aiLlmsFullDottxtRoute
  '/(ai)/llms.txt': typeof aiLlmsDottxtRoute
  '/(ai)/{$}.md': typeof aiChar123Char125DotmdRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/llms-full.txt' | '/llms.txt' | '/{$}.md' | '/api/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/llms-full.txt' | '/llms.txt' | '/{$}.md' | '/api/search'
  id:
    | '__root__'
    | '/$'
    | '/(ai)/llms-full.txt'
    | '/(ai)/llms.txt'
    | '/(ai)/{$}.md'
    | '/api/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  aiLlmsFullDottxtRoute: typeof aiLlmsFullDottxtRoute
  aiLlmsDottxtRoute: typeof aiLlmsDottxtRoute
  aiChar123Char125DotmdRoute: typeof aiChar123Char125DotmdRoute
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ai)/llms-full.txt': {
      id: '/(ai)/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof aiLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ai)/llms.txt': {
      id: '/(ai)/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof aiLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(ai)/{$}.md': {
      id: '/(ai)/{$}.md'
      path: '/{$}.md'
      fullPath: '/{$}.md'
      preLoaderRoute: typeof aiChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  aiLlmsFullDottxtRoute: aiLlmsFullDottxtRoute,
  aiLlmsDottxtRoute: aiLlmsDottxtRoute,
  aiChar123Char125DotmdRoute: aiChar123Char125DotmdRoute,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
